### ISSUE TITLE
gitpod issue

### ISSUE THREAD

**Issue by j2l** [joshnuss/supabase-sveltekit-example#1]
Hello,
I don't get how to test your project using gitpod. In the console, I get:
```
gitpod /workspace/supabase-sveltekit-example $ npm run dev

> sveltekit-example@0.0.1 dev /workspace/supabase-sveltekit-example
> svelte-kit dev

svelte.config.cjs should be renamed to svelte.config.js and converted to an ES module. See https://kit.svelte.dev/docs#configuration for an example
No "exports" main defined in /workspace/supabase-sveltekit-example/node_modules/@sveltejs/adapter-node/package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /workspace/supabase-sveltekit-example/node_modules/@sveltejs/adapter-node/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:479:7)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/workspace/supabase-sveltekit-example/svelte.config.cjs:2:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sveltekit-example@0.0.1 dev: `svelte-kit dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sveltekit-example@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitpod/.npm/_logs/2021-05-11T08_34_49_884Z-debug.log
gitpod /workspace/supabase-sveltekit-example $
```
I watched the gitpod.io video from sept 2020, but I don't have any preview window.
Sorry, but I'm new to gitpod :)

**Comment by joshnuss** [comment]
Hi @j2l,

I think the error is due to it using a newer version of svelte-kit, so some things need changing. I'll put a fix out soon,

**Comment by j2l** [comment]
Fantastic! Thank you!
Watching your https://1000experiments.dev/, you're a machine or a freakin' fast dev!
I subscribed to your experiments (realistis, have a look, in French).
Go Habs go!


Feel free to close this ticket.

**Comment by joshnuss** [comment]
Thanks for joining!

I bumped the version and it should be working now, let me know if you run into any issues with it.

and go habs go! :canada: :ice_hockey: :medal_sports:
