### ISSUE TITLE
gitpod almost there, Cannot read property 'length' of null

### ISSUE THREAD

**Issue by j2l** [joshnuss/supabase-sveltekit-example#2]
Hey,
So now, it's running but I get:
```
500
Cannot read property 'length' of null

TypeError: Cannot read property 'length' of null
    at index.svelte:20:31
    at Object.$$render (/workspace/supabase-sveltekit-example/node_modules/svelte/internal/index.js:1380:22)
    at Object.default (root.svelte:38:46)
    at eval (/workspace/supabase-sveltekit-example/src/routes/__layout.svelte:11:41)
    at Object.$$render (/workspace/supabase-sveltekit-example/node_modules/svelte/internal/index.js:1380:22)
    at root.svelte:36:44
    at $$render (/workspace/supabase-sveltekit-example/node_modules/svelte/internal/index.js:1380:22)
    at Object.render (/workspace/supabase-sveltekit-example/node_modules/svelte/internal/index.js:1388:26)
    at render_response (file:///workspace/supabase-sveltekit-example/node_modules/@sveltejs/kit/dist/ssr.js:377:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
.env file is populated

**Comment by j2l** [comment]
oh yeah, I'm missing the products table

**Comment by j2l** [comment]
do you have the supabase SQL script by any chance?
May be the table name (and fields?) should be in .env to be called by the example.
Man, your SQL generator is dope!

**Comment by joshnuss** [comment]
Thanks @j2l, glad you like it :grin: 

You can try the SQL from here: https://1000experiments.dev/posts/supabase-svelte-cart#database

**Comment by joshnuss** [comment]
Closing, since the issue should now be resolved.
